globalThis.GENERATED_SENTENCE_BANK = [
  {"grade":1,"sentence":"I go to school.","usedWords":["i","go","to","school"]},
  {"grade":1,"sentence":"What is this?","usedWords":["what","is","this"]},
  {"grade":1,"sentence":"Look at me.","usedWords":["look","at","me"]},
  {"grade":1,"sentence":"Is it hot?","usedWords":["is","it","hot"]},
  {"grade":1,"sentence":"I can play.","usedWords":["i","can","play"]},
  {"grade":1,"sentence":"Come and see.","usedWords":["come","and","see"]},
  {"grade":1,"sentence":"We like school.","usedWords":["we","like","school"]},
  {"grade":1,"sentence":"She is good.","usedWords":["she","is","good"]},
  {"grade":1,"sentence":"I am happy.","usedWords":["i","am","happy"]},
  {"grade":1,"sentence":"It is big.","usedWords":["it","is","big"]},
  {"grade":1,"sentence":"I am sad.","usedWords":["i","am","sad"]},
  {"grade":1,"sentence":"He can go.","usedWords":["he","can","go"]},
  {"grade":1,"sentence":"It is cold.","usedWords":["it","is","cold"]},
  {"grade":1,"sentence":"I like it.","usedWords":["i","like","it"]},
  {"grade":1,"sentence":"She can see.","usedWords":["she","can","see"]},
  {"grade":1,"sentence":"Who is that?","usedWords":["who","is","that"]},
  {"grade":1,"sentence":"Yes, I can.","usedWords":["yes","i","can"]},
  {"grade":1,"sentence":"He is slow.","usedWords":["he","is","slow"]},
  {"grade":1,"sentence":"We go home.","usedWords":["we","go","home"]},
  {"grade":1,"sentence":"I am at home.","usedWords":["i","am","at","home"]},
  {"grade":1,"sentence":"She is happy.","usedWords":["she","is","happy"]},
  {"grade":1,"sentence":"It is small.","usedWords":["it","is","small"]},
  {"grade":1,"sentence":"I see you.","usedWords":["i","see","you"]},
  {"grade":1,"sentence":"I like you.","usedWords":["i","like","you"]},
  {"grade":1,"sentence":"Go to class.","usedWords":["go","to","class"]},
  {"grade":1,"sentence":"I need help.","usedWords":["i","need","help"]},
  {"grade":1,"sentence":"That is my book.","usedWords":["that","is","my","book"]},
  {"grade":1,"sentence":"I am fast.","usedWords":["i","am","fast"]},
  {"grade":1,"sentence":"We are good.","usedWords":["we","are","good"]},
  {"grade":1,"sentence":"It is on top.","usedWords":["it","is","on","top"]},
  {"grade":1,"sentence":"I see mud.","usedWords":["i","see","mud"]},
  {"grade":1,"sentence":"A jet is fast.","usedWords":["a","jet","is","fast"]},
  {"grade":1,"sentence":"A hen is small.","usedWords":["a","hen","is","small"]},
  {"grade":1,"sentence":"Look at the van.","usedWords":["look","at","the","van"]},
  {"grade":1,"sentence":"The dam is big.","usedWords":["the","dam","is","big"]},
  {"grade":1,"sentence":"That is bad.","usedWords":["that","is","bad"]},
  {"grade":1,"sentence":"I am in class.","usedWords":["i","am","in","class"]},
  {"grade":1,"sentence":"I see it now.","usedWords":["i","see","it","now"]},
  {"grade":1,"sentence":"We are at school.","usedWords":["we","are","at","school"]},
  {"grade":1,"sentence":"It is my pencil.","usedWords":["it","is","my","pencil"]},
  {"grade":1,"sentence":"I am your friend.","usedWords":["i","am","your","friend"]},
  {"grade":1,"sentence":"She can come.","usedWords":["she","can","come"]},
  {"grade":1,"sentence":"They are good.","usedWords":["they","are","good"]},
  {"grade":1,"sentence":"He is my friend.","usedWords":["he","is","my","friend"]},
  {"grade":1,"sentence":"Look at her lip.","usedWords":["look","at","her","lip"]},
  {"grade":1,"sentence":"No, I am sad.","usedWords":["no","i","am","sad"]},
  {"grade":1,"sentence":"Please help me.","usedWords":["please","help","me"]},
  {"grade":1,"sentence":"She is so good.","usedWords":["she","is","so","good"]},
  {"grade":1,"sentence":"I need one pencil.","usedWords":["i","need","one","pencil"]},
  {"grade":1,"sentence":"She can help.","usedWords":["she","can","help"]},
  {"grade":2,"sentence":"What time is it today?","usedWords":["what","time","is","it","today"]},
  {"grade":2,"sentence":"Where is my pencil now?","usedWords":["where","is","my","pencil","now"]},
  {"grade":2,"sentence":"She can help me today.","usedWords":["she","can","help","me","today"]},
  {"grade":2,"sentence":"Do you have it now?","usedWords":["do","you","have","it","now"]},
  {"grade":2,"sentence":"He is my good friend.","usedWords":["he","is","my","good","friend"]},
  {"grade":2,"sentence":"I want to go home.","usedWords":["i","want","to","go","home"]},
  {"grade":2,"sentence":"We go to school today.","usedWords":["we","go","to","school","today"]},
  {"grade":2,"sentence":"Can you see my book?","usedWords":["can","you","see","my","book"]},
  {"grade":2,"sentence":"I need help at school.","usedWords":["i","need","help","at","school"]},
  {"grade":2,"sentence":"Look at your desk now.","usedWords":["look","at","your","desk","now"]},
  {"grade":2,"sentence":"Is that your pencil now?","usedWords":["is","that","your","pencil","now"]},
  {"grade":2,"sentence":"She is a good student.","usedWords":["she","is","a","good","student"]},
  {"grade":2,"sentence":"We come to class today.","usedWords":["we","come","to","class","today"]},
  {"grade":2,"sentence":"He is in my class.","usedWords":["he","is","in","my","class"]},
  {"grade":2,"sentence":"I am happy at school.","usedWords":["i","am","happy","at","school"]},
  {"grade":2,"sentence":"I am so happy today.","usedWords":["i","am","so","happy","today"]},
  {"grade":2,"sentence":"We all go to class.","usedWords":["we","all","go","to","class"]},
  {"grade":2,"sentence":"Please help me at school.","usedWords":["please","help","me","at","school"]},
  {"grade":2,"sentence":"She can take your book.","usedWords":["she","can","take","your","book"]},
  {"grade":2,"sentence":"I see you at school.","usedWords":["i","see","you","at","school"]},
  {"grade":2,"sentence":"What is in your desk?","usedWords":["what","is","in","your","desk"]},
  {"grade":2,"sentence":"He can come to class.","usedWords":["he","can","come","to","class"]},
  {"grade":2,"sentence":"I want to play now.","usedWords":["i","want","to","play","now"]},
  {"grade":2,"sentence":"Your teacher is so good.","usedWords":["your","teacher","is","so","good"]},
  {"grade":2,"sentence":"I have a good book.","usedWords":["i","have","a","good","book"]},
  {"grade":2,"sentence":"That book is on top.","usedWords":["that","book","is","on","top"]},
  {"grade":2,"sentence":"The van is so big.","usedWords":["the","van","is","so","big"]},
  {"grade":2,"sentence":"A jet is so fast.","usedWords":["a","jet","is","so","fast"]},
  {"grade":2,"sentence":"The hen is at home.","usedWords":["the","hen","is","at","home"]},
  {"grade":2,"sentence":"Look at the big dam.","usedWords":["look","at","the","big","dam"]},
  {"grade":2,"sentence":"I get help from you.","usedWords":["i","get","help","from","you"]},
  {"grade":2,"sentence":"I am your good friend.","usedWords":["i","am","your","good","friend"]},
  {"grade":2,"sentence":"Is your family at home?","usedWords":["is","your","family","at","home"]},
  {"grade":2,"sentence":"I see mud on top.","usedWords":["i","see","mud","on","top"]},
  {"grade":2,"sentence":"We play at home today.","usedWords":["we","play","at","home","today"]},
  {"grade":2,"sentence":"What do you know now?","usedWords":["what","do","you","know","now"]},
  {"grade":2,"sentence":"He is at the desk.","usedWords":["he","is","at","the","desk"]},
  {"grade":2,"sentence":"They go to school now.","usedWords":["they","go","to","school","now"]},
  {"grade":2,"sentence":"I know which book you want.","usedWords":["i","know","which","book","you","want"]},
  {"grade":2,"sentence":"Is it hot or cold?","usedWords":["is","it","hot","or","cold"]},
  {"grade":2,"sentence":"I like school but she is sad.","usedWords":["i","like","school","but","she","is","sad"]},
  {"grade":2,"sentence":"Yesterday we go to school.","usedWords":["yesterday","we","go","to","school"]},
  {"grade":2,"sentence":"Tomorrow I come to class.","usedWords":["tomorrow","i","come","to","class"]},
  {"grade":2,"sentence":"I go to school again.","usedWords":["i","go","to","school","again"]},
  {"grade":2,"sentence":"I want to come home soon.","usedWords":["i","want","to","come","home","soon"]},
  {"grade":2,"sentence":"His book is on my desk.","usedWords":["his","book","is","on","my","desk"]},
  {"grade":2,"sentence":"I go, then you come.","usedWords":["i","go","then","you","come"]},
  {"grade":2,"sentence":"I want this for you.","usedWords":["i","want","this","for","you"]},
  {"grade":2,"sentence":"Please go with me now.","usedWords":["please","go","with","me","now"]},
  {"grade":2,"sentence":"I see two or three.","usedWords":["i","see","two","or","three"]},
  {"grade":3,"sentence":"I always help my friend at school.","usedWords":["i","always","help","my","friend","at","school"]},
  {"grade":3,"sentence":"What time do we go to class?","usedWords":["what","time","do","we","go","to","class"]},
  {"grade":3,"sentence":"I think this book is so good.","usedWords":["i","think","this","book","is","so","good"]},
  {"grade":3,"sentence":"Can you help me at my desk?","usedWords":["can","you","help","me","at","my","desk"]},
  {"grade":3,"sentence":"She can make my family so happy.","usedWords":["she","can","make","my","family","so","happy"]},
  {"grade":3,"sentence":"I want to get help from you.","usedWords":["i","want","to","get","help","from","you"]},
  {"grade":3,"sentence":"Do you know where my teacher is?","usedWords":["do","you","know","where","my","teacher","is"]},
  {"grade":3,"sentence":"We like to play at home now.","usedWords":["we","like","to","play","at","home","now"]},
  {"grade":3,"sentence":"Please help me take my book home.","usedWords":["please","help","me","take","my","book","home"]},
  {"grade":3,"sentence":"She is always good to my friend.","usedWords":["she","is","always","good","to","my","friend"]},
  {"grade":3,"sentence":"I think we need to help more.","usedWords":["i","think","we","need","to","help","more"]},
  {"grade":3,"sentence":"Where is your book and your pencil?","usedWords":["where","is","your","book","and","your","pencil"]},
  {"grade":3,"sentence":"We all need to come to class.","usedWords":["we","all","need","to","come","to","class"]},
  {"grade":3,"sentence":"What do you have in your desk?","usedWords":["what","do","you","have","in","your","desk"]},
  {"grade":3,"sentence":"I like to come to school today.","usedWords":["i","like","to","come","to","school","today"]},
  {"grade":3,"sentence":"She can take your book to class.","usedWords":["she","can","take","your","book","to","class"]},
  {"grade":3,"sentence":"That big van is so fast today.","usedWords":["that","big","van","is","so","fast","today"]},
  {"grade":3,"sentence":"I see mud on top of that.","usedWords":["i","see","mud","on","top","of","that"]},
  {"grade":3,"sentence":"The jet is so fast and big.","usedWords":["the","jet","is","so","fast","and","big"]},
  {"grade":3,"sentence":"We need to know how to help.","usedWords":["we","need","to","know","how","to","help"]},
  {"grade":3,"sentence":"I want to use your pencil now.","usedWords":["i","want","to","use","your","pencil","now"]},
  {"grade":3,"sentence":"What time is it at your school?","usedWords":["what","time","is","it","at","your","school"]},
  {"grade":3,"sentence":"I always want to help my friend.","usedWords":["i","always","want","to","help","my","friend"]},
  {"grade":3,"sentence":"We can get your book from home.","usedWords":["we","can","get","your","book","from","home"]},
  {"grade":3,"sentence":"Do you like to play at home?","usedWords":["do","you","like","to","play","at","home"]},
  {"grade":3,"sentence":"I think she is a good teacher.","usedWords":["i","think","she","is","a","good","teacher"]},
  {"grade":3,"sentence":"He is always at school on time.","usedWords":["he","is","always","at","school","on","time"]},
  {"grade":3,"sentence":"Please take your book to my desk.","usedWords":["please","take","your","book","to","my","desk"]},
  {"grade":3,"sentence":"I often see my friend at school.","usedWords":["i","often","see","my","friend","at","school"]},
  {"grade":3,"sentence":"We need your help with this now.","usedWords":["we","need","your","help","with","this","now"]},
  {"grade":3,"sentence":"I see a hen on top of that.","usedWords":["i","see","a","hen","on","top","of","that"]},
  {"grade":3,"sentence":"The big dam is so cold now.","usedWords":["the","big","dam","is","so","cold","now"]},
  {"grade":3,"sentence":"She is sad about her lip now.","usedWords":["she","is","sad","about","her","lip","now"]},
  {"grade":3,"sentence":"We are often happy at home now.","usedWords":["we","are","often","happy","at","home","now"]},
  {"grade":3,"sentence":"Where is my good friend from school?","usedWords":["where","is","my","good","friend","from","school"]},
  {"grade":3,"sentence":"I am sometimes sad at home now.","usedWords":["i","am","sometimes","sad","at","home","now"]},
  {"grade":3,"sentence":"What do you like about your class?","usedWords":["what","do","you","like","about","your","class"]},
  {"grade":3,"sentence":"We have to go to school now.","usedWords":["we","have","to","go","to","school","now"]},
  {"grade":3,"sentence":"I want to know about your family.","usedWords":["i","want","to","know","about","your","family"]},
  {"grade":3,"sentence":"I need to use this at school.","usedWords":["i","need","to","use","this","at","school"]},
  {"grade":3,"sentence":"We come to school more often now.","usedWords":["we","come","to","school","more","often","now"]},
  {"grade":3,"sentence":"I go to school and come home.","usedWords":["i","go","to","school","and","come","home"]},
  {"grade":3,"sentence":"I go, then you come home today.","usedWords":["i","go","then","you","come","home","today"]},
  {"grade":3,"sentence":"Yesterday I go to school again.","usedWords":["yesterday","i","go","to","school","again"]},
  {"grade":3,"sentence":"I have some time to help you.","usedWords":["i","have","some","time","to","help","you"]},
  {"grade":3,"sentence":"I have two of this for you.","usedWords":["i","have","two","of","this","for","you"]},
  {"grade":3,"sentence":"I need three of this now.","usedWords":["i","need","three","of","this","now"]},
  {"grade":3,"sentence":"I think many of you are good.","usedWords":["i","think","many","of","you","are","good"]},
  {"grade":3,"sentence":"We go home soon and we play.","usedWords":["we","go","home","soon","and","play"]},
  {"grade":3,"sentence":"She sometimes go home to help her family.","usedWords":["she","sometimes","go","home","to","help","her","family"]},
  {"grade":4,"sentence":"I like to help my teacher when we are in class.","usedWords":["i","like","to","help","my","teacher","when","we","are","in","class"]},
  {"grade":4,"sentence":"She can always help you with your book at school.","usedWords":["she","can","always","help","you","with","your","book","at","school"]},
  {"grade":4,"sentence":"We need to think about how to help your friend.","usedWords":["we","need","to","think","about","how","to","help","your","friend"]},
  {"grade":4,"sentence":"I think school is where you make a good friend.","usedWords":["i","think","school","is","where","you","make","a","good","friend"]},
  {"grade":4,"sentence":"Where do you go when it is so hot today?","usedWords":["where","do","you","go","when","it","is","so","hot","today"]},
  {"grade":4,"sentence":"She can sometimes help the student who need it most.","usedWords":["she","can","sometimes","help","the","student","who","need","it","most"]},
  {"grade":4,"sentence":"I want to know how to use this book at home.","usedWords":["i","want","to","know","how","to","use","this","book","at","home"]},
  {"grade":4,"sentence":"He always come to school and is so happy every time.","usedWords":["he","always","come","to","school","and","is","so","happy","every","time"]},
  {"grade":4,"sentence":"I need to get my pencil from the desk at school.","usedWords":["i","need","to","get","my","pencil","from","the","desk","at","school"]},
  {"grade":4,"sentence":"Please help me take your big book home from school.","usedWords":["please","help","me","take","your","big","book","home","from","school"]},
  {"grade":4,"sentence":"What time do we come to class to help the student?","usedWords":["what","time","do","we","come","to","class","to","help","the","student"]},
  {"grade":4,"sentence":"I think she is the most happy student in class.","usedWords":["i","think","she","is","the","most","happy","student","in","class"]},
  {"grade":4,"sentence":"We always go to school and come home on time.","usedWords":["we","always","go","to","school","and","come","home","on","time"]},
  {"grade":4,"sentence":"Do you know what time we need to go to school?","usedWords":["do","you","know","what","time","we","need","to","go","to","school"]},
  {"grade":4,"sentence":"I want to help my family and my good friend today.","usedWords":["i","want","to","help","my","family","and","my","good","friend","today"]},
  {"grade":4,"sentence":"She always help your family when they need to get help.","usedWords":["she","always","help","your","family","when","they","need","to","get","help"]},
  {"grade":4,"sentence":"It is always good to help your family at home.","usedWords":["it","is","always","good","to","help","your","family","at","home"]},
  {"grade":4,"sentence":"Please take this big book from my desk to your teacher.","usedWords":["please","take","this","big","book","from","my","desk","to","your","teacher"]},
  {"grade":4,"sentence":"I sometimes think about my school and my good teacher.","usedWords":["i","sometimes","think","about","my","school","and","my","good","teacher"]},
  {"grade":4,"sentence":"We need to come to class on time more often.","usedWords":["we","need","to","come","to","class","on","time","more","often"]},
  {"grade":4,"sentence":"I want to know how my friend is at school.","usedWords":["i","want","to","know","how","my","friend","is","at","school"]},
  {"grade":4,"sentence":"Can you help me use this pencil at my desk?","usedWords":["can","you","help","me","use","this","pencil","at","my","desk"]},
  {"grade":4,"sentence":"I think it is so good to help at school.","usedWords":["i","think","it","is","so","good","to","help","at","school"]},
  {"grade":4,"sentence":"She can take the big book and go to class now.","usedWords":["she","can","take","the","big","book","and","go","to","class","now"]},
  {"grade":4,"sentence":"We have to get your book from the desk now.","usedWords":["we","have","to","get","your","book","from","the","desk","now"]},
  {"grade":4,"sentence":"I like to think about how to make my friend happy.","usedWords":["i","like","to","think","about","how","to","make","my","friend","happy"]},
  {"grade":4,"sentence":"Your teacher can help you use your book and your pencil.","usedWords":["your","teacher","can","help","you","use","your","book","and","your","pencil"]},
  {"grade":4,"sentence":"What do you think about your school and your class now?","usedWords":["what","do","you","think","about","your","school","and","your","class","now"]},
  {"grade":4,"sentence":"I always help the student at my desk in class.","usedWords":["i","always","help","the","student","at","my","desk","in","class"]},
  {"grade":4,"sentence":"We want to go home and help your family today.","usedWords":["we","want","to","go","home","and","help","your","family","today"]},
  {"grade":4,"sentence":"I see a big van and a jet at school.","usedWords":["i","see","a","big","van","and","a","jet","at","school"]},
  {"grade":4,"sentence":"The jet is so fast and the van is slow now.","usedWords":["the","jet","is","so","fast","and","the","van","is","slow","now"]},
  {"grade":4,"sentence":"We go to see the big dam from your school.","usedWords":["we","go","to","see","the","big","dam","from","your","school"]},
  {"grade":4,"sentence":"She can see the mud on top of the dam now.","usedWords":["she","can","see","the","mud","on","top","of","the","dam","now"]},
  {"grade":4,"sentence":"I see a hen on top and it is small.","usedWords":["i","see","a","hen","on","top","and","it","is","small"]},
  {"grade":4,"sentence":"She can help me with my lip at home.","usedWords":["she","can","help","me","with","my","lip","at","home"]},
  {"grade":4,"sentence":"What time do we go home and see your family?","usedWords":["what","time","do","we","go","home","and","see","your","family"]},
  {"grade":4,"sentence":"I think we need to make a good time at school.","usedWords":["i","think","we","need","to","make","a","good","time","at","school"]},
  {"grade":4,"sentence":"Please help me take this big book to your teacher now.","usedWords":["please","help","me","take","this","big","book","to","your","teacher","now"]},
  {"grade":4,"sentence":"She always come to class and she is so happy today.","usedWords":["she","always","come","to","class","and","she","is","so","happy","today"]},
  {"grade":4,"sentence":"We often go home and help your family with so much.","usedWords":["we","often","go","home","and","help","your","family","with","so","much"]},
  {"grade":4,"sentence":"I know you are a good student at your school.","usedWords":["i","know","you","are","a","good","student","at","your","school"]},
  {"grade":4,"sentence":"Can you help me get this book from your desk now?","usedWords":["can","you","help","me","get","this","book","from","your","desk","now"]},
  {"grade":4,"sentence":"I want to think about how to help your family now.","usedWords":["i","want","to","think","about","how","to","help","your","family","now"]},
  {"grade":4,"sentence":"We always play at home when it is so hot today.","usedWords":["we","always","play","at","home","when","it","is","so","hot","today"]},
  {"grade":4,"sentence":"She sometimes need to take your book to the class.","usedWords":["she","sometimes","need","to","take","your","book","to","the","class"]},
  {"grade":4,"sentence":"I often think about my family when I am at school.","usedWords":["i","often","think","about","my","family","when","i","am","at","school"]},
  {"grade":4,"sentence":"Do you know how to use this book for your class?","usedWords":["do","you","know","how","to","use","this","book","for","your","class"]},
  {"grade":4,"sentence":"What time do we need to come to school today?","usedWords":["what","time","do","we","need","to","come","to","school","today"]},
  {"grade":4,"sentence":"I think your family is so good and happy at home.","usedWords":["i","think","your","family","is","so","good","and","happy","at","home"]},
  {"grade":5,"sentence":"I always want to help my friend at school and at home.","usedWords":["i","always","want","to","help","my","friend","at","school","and","home"]},
  {"grade":5,"sentence":"She always know how to make your family and friend so happy.","usedWords":["she","always","know","how","to","make","your","family","and","friend","so","happy"]},
  {"grade":5,"sentence":"We need to come to school every time so we can know more.","usedWords":["we","need","to","come","to","school","every","time","so","we","can","know","more"]},
  {"grade":5,"sentence":"Where do you go when it is so hot and you want help?","usedWords":["where","do","you","go","when","it","is","so","hot","and","you","want","help"]},
  {"grade":5,"sentence":"I think you need to come to class every time to know more.","usedWords":["i","think","you","need","to","come","to","class","every","time","to","know","more"]},
  {"grade":5,"sentence":"She always help your friend and family when they need so much.","usedWords":["she","always","help","your","friend","and","family","when","they","need","so","much"]},
  {"grade":5,"sentence":"I want to know where my teacher go when we are at school.","usedWords":["i","want","to","know","where","my","teacher","go","when","we","are","at","school"]},
  {"grade":5,"sentence":"Can you help me take this book from my desk to your teacher?","usedWords":["can","you","help","me","take","this","book","from","my","desk","to","your","teacher"]},
  {"grade":5,"sentence":"He want to know how to use every book in the school.","usedWords":["he","want","to","know","how","to","use","every","book","in","the","school"]},
  {"grade":5,"sentence":"I like to think about how to make my family happy at home.","usedWords":["i","like","to","think","about","how","to","make","my","family","happy","at","home"]},
  {"grade":5,"sentence":"We always come to school and take your book to the desk.","usedWords":["we","always","come","to","school","and","take","your","book","to","the","desk"]},
  {"grade":5,"sentence":"Do you know where your teacher and your family go on time?","usedWords":["do","you","know","where","your","teacher","and","your","family","go","on","time"]},
  {"grade":5,"sentence":"It is so good to help your family at home all the time.","usedWords":["it","is","so","good","to","help","your","family","at","home","all","the","time"]},
  {"grade":5,"sentence":"She can take your big book from the desk and go to class.","usedWords":["she","can","take","your","big","book","from","the","desk","and","go","to","class"]},
  {"grade":5,"sentence":"I always want to help my student and my friend at school.","usedWords":["i","always","want","to","help","my","student","and","my","friend","at","school"]},
  {"grade":5,"sentence":"We need to know how to get more help from your teacher.","usedWords":["we","need","to","know","how","to","get","more","help","from","your","teacher"]},
  {"grade":5,"sentence":"I think you need to help your family and friend at home.","usedWords":["i","think","you","need","to","help","your","family","and","friend","at","home"]},
  {"grade":5,"sentence":"She sometimes want to go home and play with your good friend.","usedWords":["she","sometimes","want","to","go","home","and","play","with","your","good","friend"]},
  {"grade":5,"sentence":"I often think about how to make my school so good for all.","usedWords":["i","often","think","about","how","to","make","my","school","so","good","for","all"]},
  {"grade":5,"sentence":"We all need to help every student in your class at school.","usedWords":["we","all","need","to","help","every","student","in","your","class","at","school"]},
  {"grade":5,"sentence":"What do you think about how to use your time at school?","usedWords":["what","do","you","think","about","how","to","use","your","time","at","school"]},
  {"grade":5,"sentence":"I want to make my teacher and my family so happy today.","usedWords":["i","want","to","make","my","teacher","and","my","family","so","happy","today"]},
  {"grade":5,"sentence":"Please help me get your big pencil from the desk to class.","usedWords":["please","help","me","get","your","big","pencil","from","the","desk","to","class"]},
  {"grade":5,"sentence":"She can sometimes see a big van and a fast jet at school.","usedWords":["she","can","sometimes","see","a","big","van","and","a","fast","jet","at","school"]},
  {"grade":5,"sentence":"I think a jet is so fast and the van is so slow.","usedWords":["i","think","a","jet","is","so","fast","and","the","van","is","so","slow"]},
  {"grade":5,"sentence":"The dam is so big and you can see mud on the top.","usedWords":["the","dam","is","so","big","and","you","can","see","mud","on","the","top"]},
  {"grade":5,"sentence":"I see a small hen on top of the dam now.","usedWords":["i","see","a","small","hen","on","top","of","the","dam","now"]},
  {"grade":5,"sentence":"She need to help her lip and take some time at home.","usedWords":["she","need","to","help","her","lip","and","take","some","time","at","home"]},
  {"grade":5,"sentence":"What time do we go home and see your family and friend?","usedWords":["what","time","do","we","go","home","and","see","your","family","and","friend"]},
  {"grade":5,"sentence":"I always want to think about how I can help at school.","usedWords":["i","always","want","to","think","about","how","i","can","help","at","school"]},
  {"grade":5,"sentence":"Do you know what to do when you want to help more?","usedWords":["do","you","know","what","to","do","when","you","want","to","help","more"]},
  {"grade":5,"sentence":"We sometimes think about how to make your class more happy today.","usedWords":["we","sometimes","think","about","how","to","make","your","class","more","happy","today"]},
  {"grade":5,"sentence":"I want to get a good book from your desk at school.","usedWords":["i","want","to","get","a","good","book","from","your","desk","at","school"]},
  {"grade":5,"sentence":"She often come to class and help every student at the desk.","usedWords":["she","often","come","to","class","and","help","every","student","at","the","desk"]},
  {"grade":5,"sentence":"We all need to know how to use your book at home.","usedWords":["we","all","need","to","know","how","to","use","your","book","at","home"]},
  {"grade":5,"sentence":"I like to help my family when they are sad at home.","usedWords":["i","like","to","help","my","family","when","they","are","sad","at","home"]},
  {"grade":5,"sentence":"Please help me take this pencil from your desk to my class.","usedWords":["please","help","me","take","this","pencil","from","your","desk","to","my","class"]},
  {"grade":5,"sentence":"What do you think about your family when you are at school?","usedWords":["what","do","you","think","about","your","family","when","you","are","at","school"]},
  {"grade":5,"sentence":"He always want to help the student who is sad at school.","usedWords":["he","always","want","to","help","the","student","who","is","sad","at","school"]},
  {"grade":5,"sentence":"Can you help me get more time to play at home today?","usedWords":["can","you","help","me","get","more","time","to","play","at","home","today"]},
  {"grade":6,"sentence":"I think you need to help your friend and family every time they are sad.","usedWords":["i","think","you","need","to","help","your","friend","and","family","every","time","they","are","sad"]},
  {"grade":6,"sentence":"She always know how to make your family and your friend so happy at home.","usedWords":["she","always","know","how","to","make","your","family","and","your","friend","so","happy","at","home"]},
  {"grade":6,"sentence":"We need to think about how we can help your friend and family every time.","usedWords":["we","need","to","think","about","how","we","can","help","your","friend","and","family","every","time"]},
  {"grade":6,"sentence":"I want to know where my teacher go when we are all at school today.","usedWords":["i","want","to","know","where","my","teacher","go","when","we","are","all","at","school","today"]},
  {"grade":6,"sentence":"She always come to class and help every student who need it so much today.","usedWords":["she","always","come","to","class","and","help","every","student","who","need","it","so","much","today"]},
  {"grade":6,"sentence":"I think we always need to know how to help every student at your school.","usedWords":["i","think","we","always","need","to","know","how","to","help","every","student","at","your","school"]},
  {"grade":6,"sentence":"Can you please help me get your big book from the desk and take it home?","usedWords":["can","you","please","help","me","get","your","big","book","from","the","desk","and","take","it","home"]},
  {"grade":6,"sentence":"She want to know how to make every student in your class so good and happy.","usedWords":["she","want","to","know","how","to","make","every","student","in","your","class","so","good","and","happy"]},
  {"grade":6,"sentence":"I often think about how to help your family when they are sad at home.","usedWords":["i","often","think","about","how","to","help","your","family","when","they","are","sad","at","home"]},
  {"grade":6,"sentence":"Where do you go when it is so hot and your family want to come home?","usedWords":["where","do","you","go","when","it","is","so","hot","and","your","family","want","to","come","home"]},
  {"grade":6,"sentence":"I always want to help every student in my class and make school so good today.","usedWords":["i","always","want","to","help","every","student","in","my","class","and","make","school","so","good","today"]},
  {"grade":6,"sentence":"We need to use every book in your school to know more and get so much.","usedWords":["we","need","to","use","every","book","in","your","school","to","know","more","and","get","so","much"]},
  {"grade":6,"sentence":"I think that your teacher is always good to every student when they need it most.","usedWords":["i","think","that","your","teacher","is","always","good","to","every","student","when","they","need","it","most"]},
  {"grade":6,"sentence":"She often want to take your good book and go home to help her family today.","usedWords":["she","often","want","to","take","your","good","book","and","go","home","to","help","her","family","today"]},
  {"grade":6,"sentence":"What time do we need to come to school and help every student at your desk?","usedWords":["what","time","do","we","need","to","come","to","school","and","help","every","student","at","your","desk"]},
  {"grade":6,"sentence":"I think we need to help your friend every time they come to class and play.","usedWords":["i","think","we","need","to","help","your","friend","every","time","they","come","to","class","and","play"]},
  {"grade":6,"sentence":"She sometimes know how to get more help from every teacher and student in your school.","usedWords":["she","sometimes","know","how","to","get","more","help","from","every","teacher","and","student","in","your","school"]},
  {"grade":6,"sentence":"I want to think about what time we need to come to class and help.","usedWords":["i","want","to","think","about","what","time","we","need","to","come","to","class","and","help"]},
  {"grade":6,"sentence":"Do you know how to make your teacher and your family so happy at school today?","usedWords":["do","you","know","how","to","make","your","teacher","and","your","family","so","happy","at","school","today"]},
  {"grade":6,"sentence":"I always come to class with your good book and your pencil every time now.","usedWords":["i","always","come","to","class","with","your","good","book","and","your","pencil","every","time","now"]},
  {"grade":6,"sentence":"We all need to help every student and teacher at your school and class every time.","usedWords":["we","all","need","to","help","every","student","and","teacher","at","your","school","and","class","every","time"]},
  {"grade":6,"sentence":"I think you always need to use your pencil and your book at school.","usedWords":["i","think","you","always","need","to","use","your","pencil","and","your","book","at","school"]},
  {"grade":6,"sentence":"Can you help me take your big book from the desk and please use it today?","usedWords":["can","you","help","me","take","your","big","book","from","the","desk","and","please","use","it","today"]},
  {"grade":6,"sentence":"She want every student in your class to have a good and happy time always.","usedWords":["she","want","every","student","in","your","class","to","have","a","good","and","happy","time","always"]},
  {"grade":6,"sentence":"I like to think about how I can help my family and friend at home today.","usedWords":["i","like","to","think","about","how","i","can","help","my","family","and","friend","at","home","today"]},
  {"grade":6,"sentence":"I see a big van and a fast jet at the top of the dam.","usedWords":["i","see","a","big","van","and","a","fast","jet","at","the","top","of","the","dam"]},
  {"grade":6,"sentence":"She can see mud on the top of the big dam and she is so sad.","usedWords":["she","can","see","mud","on","the","top","of","the","big","dam","and","she","is","so","sad"]},
  {"grade":6,"sentence":"I think the small hen at the top of the dam is so good and happy.","usedWords":["i","think","the","small","hen","at","the","top","of","the","dam","is","so","good","and","happy"]},
  {"grade":6,"sentence":"My lip is sad and I always need to get help from my teacher at school.","usedWords":["my","lip","is","sad","and","i","always","need","to","get","help","from","my","teacher","at","school"]},
  {"grade":6,"sentence":"She want to help the small hen on top and she need so much help today.","usedWords":["she","want","to","help","the","small","hen","on","top","and","she","need","so","much","help","today"]},
  {"grade":6,"sentence":"I always want to know how to use my book when I am at school.","usedWords":["i","always","want","to","know","how","to","use","my","book","when","i","am","at","school"]},
  {"grade":6,"sentence":"We need to help every good student in your class and make your school so happy.","usedWords":["we","need","to","help","every","good","student","in","your","class","and","make","your","school","so","happy"]},
  {"grade":6,"sentence":"I think about how to help your family when they are sad and need so much.","usedWords":["i","think","about","how","to","help","your","family","when","they","are","sad","and","need","so","much"]},
  {"grade":6,"sentence":"Do you know what to do when your family and friend need help at home?","usedWords":["do","you","know","what","to","do","when","your","family","and","friend","need","help","at","home"]},
  {"grade":6,"sentence":"She often come to your school and help every student and teacher with so much.","usedWords":["she","often","come","to","your","school","and","help","every","student","and","teacher","with","so","much"]}
];
