globalThis.GENERATED_SENTENCE_BANK = [
  {"grade":1,"sentence":"I go to school.","usedWords":["i","go","to","school"]},
  {"grade":1,"sentence":"What is this?","usedWords":["what","is","this"]},
  {"grade":1,"sentence":"Look at me.","usedWords":["look","at","me"]},
  {"grade":1,"sentence":"Is it hot?","usedWords":["is","it","hot"]},
  {"grade":1,"sentence":"I can play.","usedWords":["i","can","play"]},
  {"grade":1,"sentence":"Come and see.","usedWords":["come","and","see"]},
  {"grade":1,"sentence":"We like school.","usedWords":["we","like","school"]},
  {"grade":1,"sentence":"She is good.","usedWords":["she","is","good"]},
  {"grade":1,"sentence":"I am happy.","usedWords":["i","am","happy"]},
  {"grade":1,"sentence":"It is big.","usedWords":["it","is","big"]},
  {"grade":1,"sentence":"I am sad.","usedWords":["i","am","sad"]},
  {"grade":1,"sentence":"He can go.","usedWords":["he","can","go"]},
  {"grade":1,"sentence":"It is cold.","usedWords":["it","is","cold"]},
  {"grade":1,"sentence":"Look at this.","usedWords":["look","at","this"]},
  {"grade":1,"sentence":"I like it.","usedWords":["i","like","it"]},
  {"grade":1,"sentence":"She can see.","usedWords":["she","can","see"]},
  {"grade":1,"sentence":"Who is that?","usedWords":["who","is","that"]},
  {"grade":1,"sentence":"Yes, I can.","usedWords":["yes","i","can"]},
  {"grade":1,"sentence":"He is slow.","usedWords":["he","is","slow"]},
  {"grade":1,"sentence":"I am a student.","usedWords":["i","am","a","student"]},
  {"grade":1,"sentence":"This is good.","usedWords":["this","is","good"]},
  {"grade":1,"sentence":"We can play.","usedWords":["we","can","play"]},
  {"grade":1,"sentence":"I like you.","usedWords":["i","like","you"]},
  {"grade":1,"sentence":"What is that?","usedWords":["what","is","that"]},
  {"grade":1,"sentence":"It is bad.","usedWords":["it","is","bad"]},
  {"grade":1,"sentence":"I see you.","usedWords":["i","see","you"]},
  {"grade":1,"sentence":"Is she happy?","usedWords":["is","she","happy"]},
  {"grade":1,"sentence":"He is big.","usedWords":["he","is","big"]},
  {"grade":1,"sentence":"Come to me.","usedWords":["come","to","me"]},
  {"grade":1,"sentence":"Use a pencil.","usedWords":["use","a","pencil"]},
  {"grade":1,"sentence":"This is my desk.","usedWords":["this","is","my","desk"]},
  {"grade":1,"sentence":"Go home now.","usedWords":["go","home","now"]},
  {"grade":1,"sentence":"He is sad.","usedWords":["he","is","sad"]},
  {"grade":1,"sentence":"We are happy.","usedWords":["we","are","happy"]},
  {"grade":1,"sentence":"She is my teacher.","usedWords":["she","is","my","teacher"]},
  {"grade":1,"sentence":"She can go fast.","usedWords":["she","can","go","fast"]},
  {"grade":1,"sentence":"Look at his book.","usedWords":["look","at","his","book"]},
  {"grade":1,"sentence":"No, I am happy.","usedWords":["no","i","am","happy"]},
  {"grade":1,"sentence":"They are good.","usedWords":["they","are","good"]},
  {"grade":1,"sentence":"It is on my desk.","usedWords":["it","is","on","my","desk"]},
  {"grade":1,"sentence":"Go to class.","usedWords":["go","to","class"]},
  {"grade":1,"sentence":"I have a book.","usedWords":["i","have","a","book"]},
  {"grade":1,"sentence":"She is my friend.","usedWords":["she","is","my","friend"]},
  {"grade":1,"sentence":"I am at home.","usedWords":["i","am","at","home"]},
  {"grade":1,"sentence":"One, two, three, go!","usedWords":["one","two","three","go"]},
  {"grade":1,"sentence":"It is so small.","usedWords":["it","is","so","small"]},
  {"grade":1,"sentence":"I am in class.","usedWords":["i","am","in","class"]},
  {"grade":1,"sentence":"What is this for?","usedWords":["what","is","this","for"]},
  {"grade":1,"sentence":"It is time.","usedWords":["it","is","time"]},
  {"grade":1,"sentence":"I use this.","usedWords":["i","use","this"]},
  {"grade":2,"sentence":"What time is it?","usedWords":["what","time","is","it"]},
  {"grade":2,"sentence":"I like your book.","usedWords":["i","like","your","book"]},
  {"grade":2,"sentence":"She can help me.","usedWords":["she","can","help","me"]},
  {"grade":2,"sentence":"Do you have it?","usedWords":["do","you","have","it"]},
  {"grade":2,"sentence":"He is my friend.","usedWords":["he","is","my","friend"]},
  {"grade":2,"sentence":"Look at the book.","usedWords":["look","at","the","book"]},
  {"grade":2,"sentence":"I want to go.","usedWords":["i","want","to","go"]},
  {"grade":2,"sentence":"Can you see me?","usedWords":["can","you","see","me"]},
  {"grade":2,"sentence":"We go to school.","usedWords":["we","go","to","school"]},
  {"grade":2,"sentence":"Where is my pencil?","usedWords":["where","is","my","pencil"]},
  {"grade":2,"sentence":"Come to my home.","usedWords":["come","to","my","home"]},
  {"grade":2,"sentence":"I need a book.","usedWords":["i","need","a","book"]},
  {"grade":2,"sentence":"Do you like this?","usedWords":["do","you","like","this"]},
  {"grade":2,"sentence":"He is at school.","usedWords":["he","is","at","school"]},
  {"grade":2,"sentence":"I like your class.","usedWords":["i","like","your","class"]},
  {"grade":2,"sentence":"We play at school.","usedWords":["we","play","at","school"]},
  {"grade":2,"sentence":"Look at your book.","usedWords":["look","at","your","book"]},
  {"grade":2,"sentence":"It is so hot.","usedWords":["it","is","so","hot"]},
  {"grade":2,"sentence":"She is a student.","usedWords":["she","is","a","student"]},
  {"grade":2,"sentence":"I see your pencil.","usedWords":["i","see","your","pencil"]},
  {"grade":2,"sentence":"We are at home.","usedWords":["we","are","at","home"]},
  {"grade":2,"sentence":"Do you want this?","usedWords":["do","you","want","this"]},
  {"grade":2,"sentence":"I know your teacher.","usedWords":["i","know","your","teacher"]},
  {"grade":2,"sentence":"He is at home.","usedWords":["he","is","at","home"]},
  {"grade":2,"sentence":"We want to play.","usedWords":["we","want","to","play"]},
  {"grade":2,"sentence":"I use a pencil.","usedWords":["i","use","a","pencil"]},
  {"grade":2,"sentence":"She can come now.","usedWords":["she","can","come","now"]},
  {"grade":2,"sentence":"Take your book home.","usedWords":["take","your","book","home"]},
  {"grade":2,"sentence":"I want your help.","usedWords":["i","want","your","help"]},
  {"grade":2,"sentence":"We see the teacher.","usedWords":["we","see","the","teacher"]},
  {"grade":2,"sentence":"Who is your friend?","usedWords":["who","is","your","friend"]},
  {"grade":2,"sentence":"My book is big.","usedWords":["my","book","is","big"]},
  {"grade":2,"sentence":"I am your friend.","usedWords":["i","am","your","friend"]},
  {"grade":2,"sentence":"Is she at school?","usedWords":["is","she","at","school"]},
  {"grade":2,"sentence":"I need your help.","usedWords":["i","need","your","help"]},
  {"grade":2,"sentence":"He can come now.","usedWords":["he","can","come","now"]},
  {"grade":2,"sentence":"Look at your desk.","usedWords":["look","at","your","desk"]},
  {"grade":2,"sentence":"We like to play.","usedWords":["we","like","to","play"]},
  {"grade":2,"sentence":"Which book do you want?","usedWords":["which","book","do","you","want"]},
  {"grade":2,"sentence":"Come to school tomorrow please.","usedWords":["come","to","school","tomorrow","please"]},
  {"grade":2,"sentence":"I am sad about yesterday.","usedWords":["i","am","sad","about","yesterday"]},
  {"grade":2,"sentence":"Yes, I can help you.","usedWords":["yes","i","can","help","you"]},
  {"grade":2,"sentence":"Come home soon please.","usedWords":["come","home","soon","please"]},
  {"grade":2,"sentence":"She is happy every time.","usedWords":["she","is","happy","every","time"]},
  {"grade":2,"sentence":"I have some time today.","usedWords":["i","have","some","time","today"]},
  {"grade":2,"sentence":"Do it again please.","usedWords":["do","it","again","please"]},
  {"grade":2,"sentence":"Is it hot or cold?","usedWords":["is","it","hot","or","cold"]},
  {"grade":2,"sentence":"I like this so much.","usedWords":["i","like","this","so","much"]},
  {"grade":2,"sentence":"She can get her book.","usedWords":["she","can","get","her","book"]},
  {"grade":2,"sentence":"How do you know this?","usedWords":["how","do","you","know","this"]},
  {"grade":3,"sentence":"What time do we go?","usedWords":["what","time","do","we","go"]},
  {"grade":3,"sentence":"I need help with this.","usedWords":["i","need","help","with","this"]},
  {"grade":3,"sentence":"Can you see my book?","usedWords":["can","you","see","my","book"]},
  {"grade":3,"sentence":"We go to school today.","usedWords":["we","go","to","school","today"]},
  {"grade":3,"sentence":"I want to go home.","usedWords":["i","want","to","go","home"]},
  {"grade":3,"sentence":"Do you like your class?","usedWords":["do","you","like","your","class"]},
  {"grade":3,"sentence":"Where is my book today?","usedWords":["where","is","my","book","today"]},
  {"grade":3,"sentence":"I want to play with you.","usedWords":["i","want","to","play","with","you"]},
  {"grade":3,"sentence":"How do you use this?","usedWords":["how","do","you","use","this"]},
  {"grade":3,"sentence":"It is so hot today.","usedWords":["it","is","so","hot","today"]},
  {"grade":3,"sentence":"She is a good student.","usedWords":["she","is","a","good","student"]},
  {"grade":3,"sentence":"I think you are good.","usedWords":["i","think","you","are","good"]},
  {"grade":3,"sentence":"He can come to my home.","usedWords":["he","can","come","to","my","home"]},
  {"grade":3,"sentence":"I get to go home.","usedWords":["i","get","to","go","home"]},
  {"grade":3,"sentence":"Where do you go today?","usedWords":["where","do","you","go","today"]},
  {"grade":3,"sentence":"I know about your book.","usedWords":["i","know","about","your","book"]},
  {"grade":3,"sentence":"She is a good friend.","usedWords":["she","is","a","good","friend"]},
  {"grade":3,"sentence":"Do you know my teacher?","usedWords":["do","you","know","my","teacher"]},
  {"grade":3,"sentence":"We can all play now.","usedWords":["we","can","all","play","now"]},
  {"grade":3,"sentence":"I want to use that.","usedWords":["i","want","to","use","that"]},
  {"grade":3,"sentence":"Look at the big book.","usedWords":["look","at","the","big","book"]},
  {"grade":3,"sentence":"Who is your class teacher?","usedWords":["who","is","your","class","teacher"]},
  {"grade":3,"sentence":"I like to go home.","usedWords":["i","like","to","go","home"]},
  {"grade":3,"sentence":"She can see the book.","usedWords":["she","can","see","the","book"]},
  {"grade":3,"sentence":"We need to go now.","usedWords":["we","need","to","go","now"]},
  {"grade":3,"sentence":"What do you think about this?","usedWords":["what","do","you","think","about","this"]},
  {"grade":3,"sentence":"He is in my class.","usedWords":["he","is","in","my","class"]},
  {"grade":3,"sentence":"Take a book to school.","usedWords":["take","a","book","to","school"]},
  {"grade":3,"sentence":"I think she is good.","usedWords":["i","think","she","is","good"]},
  {"grade":3,"sentence":"We play at school today.","usedWords":["we","play","at","school","today"]},
  {"grade":3,"sentence":"Can you help me please?","usedWords":["can","you","help","me","please"]},
  {"grade":3,"sentence":"She is at home now.","usedWords":["she","is","at","home","now"]},
  {"grade":3,"sentence":"What do you have today?","usedWords":["what","do","you","have","today"]},
  {"grade":3,"sentence":"I like to use this.","usedWords":["i","like","to","use","this"]},
  {"grade":3,"sentence":"I think about my family.","usedWords":["i","think","about","my","family"]},
  {"grade":3,"sentence":"Where is your teacher now?","usedWords":["where","is","your","teacher","now"]},
  {"grade":3,"sentence":"He can get your book.","usedWords":["he","can","get","your","book"]},
  {"grade":3,"sentence":"I am at home today.","usedWords":["i","am","at","home","today"]},
  {"grade":3,"sentence":"I like school most of all.","usedWords":["i","like","school","most","of","all"]},
  {"grade":3,"sentence":"Come to class and then go.","usedWords":["come","to","class","and","then","go"]},
  {"grade":3,"sentence":"I like it but it is hot.","usedWords":["i","like","it","but","is","hot"]},
  {"grade":3,"sentence":"I often go to school.","usedWords":["i","often","go","to","school"]},
  {"grade":3,"sentence":"I sometimes play at home.","usedWords":["i","sometimes","play","at","home"]},
  {"grade":3,"sentence":"I need more time today.","usedWords":["i","need","more","time","today"]},
  {"grade":3,"sentence":"I want to help many of you.","usedWords":["i","want","to","help","many","of","you"]},
  {"grade":3,"sentence":"Take this book from me.","usedWords":["take","this","book","from","me"]},
  {"grade":3,"sentence":"I know all of this.","usedWords":["i","know","all","of","this"]},
  {"grade":3,"sentence":"How do you make this?","usedWords":["how","do","you","make","this"]},
  {"grade":3,"sentence":"When do you go home?","usedWords":["when","do","you","go","home"]},
  {"grade":3,"sentence":"I want to know more.","usedWords":["i","want","to","know","more"]},
  {"grade":4,"sentence":"What time do we go home?","usedWords":["what","time","do","we","go","home"]},
  {"grade":4,"sentence":"I always need help at school.","usedWords":["i","always","need","help","at","school"]},
  {"grade":4,"sentence":"Can you take my pencil please?","usedWords":["can","you","take","my","pencil","please"]},
  {"grade":4,"sentence":"How do you use this pencil?","usedWords":["how","do","you","use","this","pencil"]},
  {"grade":4,"sentence":"I think she is a good teacher.","usedWords":["i","think","she","is","a","good","teacher"]},
  {"grade":4,"sentence":"I need to go home now.","usedWords":["i","need","to","go","home","now"]},
  {"grade":4,"sentence":"I like to play at school.","usedWords":["i","like","to","play","at","school"]},
  {"grade":4,"sentence":"What do you know about this?","usedWords":["what","do","you","know","about","this"]},
  {"grade":4,"sentence":"She can see my big book.","usedWords":["she","can","see","my","big","book"]},
  {"grade":4,"sentence":"We need to take this home.","usedWords":["we","need","to","take","this","home"]},
  {"grade":4,"sentence":"I want to help my teacher.","usedWords":["i","want","to","help","my","teacher"]},
  {"grade":4,"sentence":"She is a good student today.","usedWords":["she","is","a","good","student","today"]},
  {"grade":4,"sentence":"We can all go home now.","usedWords":["we","can","all","go","home","now"]},
  {"grade":4,"sentence":"I like to get help at school.","usedWords":["i","like","to","get","help","at","school"]},
  {"grade":4,"sentence":"I know where your family is from.","usedWords":["i","know","where","your","family","is","from"]},
  {"grade":4,"sentence":"Do you want to come home?","usedWords":["do","you","want","to","come","home"]},
  {"grade":4,"sentence":"I think you are a good friend.","usedWords":["i","think","you","are","a","good","friend"]},
  {"grade":4,"sentence":"She can come to my class.","usedWords":["she","can","come","to","my","class"]},
  {"grade":4,"sentence":"I always want to help you.","usedWords":["i","always","want","to","help","you"]},
  {"grade":4,"sentence":"How do you know my friend?","usedWords":["how","do","you","know","my","friend"]},
  {"grade":4,"sentence":"We need to help the student.","usedWords":["we","need","to","help","the","student"]},
  {"grade":4,"sentence":"I often get help from my teacher.","usedWords":["i","often","get","help","from","my","teacher"]},
  {"grade":4,"sentence":"Look at this big school today.","usedWords":["look","at","this","big","school","today"]},
  {"grade":4,"sentence":"Do you think about your family?","usedWords":["do","you","think","about","your","family"]},
  {"grade":4,"sentence":"She can see my small desk.","usedWords":["she","can","see","my","small","desk"]},
  {"grade":4,"sentence":"We always like to help you.","usedWords":["we","always","like","to","help","you"]},
  {"grade":4,"sentence":"I want to use your pencil.","usedWords":["i","want","to","use","your","pencil"]},
  {"grade":4,"sentence":"What do you know about school?","usedWords":["what","do","you","know","about","school"]},
  {"grade":4,"sentence":"She is happy to help me.","usedWords":["she","is","happy","to","help","me"]},
  {"grade":4,"sentence":"I need to take this home.","usedWords":["i","need","to","take","this","home"]},
  {"grade":4,"sentence":"We can all come home now.","usedWords":["we","can","all","come","home","now"]},
  {"grade":4,"sentence":"How do you make it fast?","usedWords":["how","do","you","make","it","fast"]},
  {"grade":4,"sentence":"I want to see your family.","usedWords":["i","want","to","see","your","family"]},
  {"grade":4,"sentence":"She is in my class today.","usedWords":["she","is","in","my","class","today"]},
  {"grade":4,"sentence":"What time do you go home?","usedWords":["what","time","do","you","go","home"]},
  {"grade":4,"sentence":"I often go to school now.","usedWords":["i","often","go","to","school","now"]},
  {"grade":4,"sentence":"We like to help my friend.","usedWords":["we","like","to","help","my","friend"]},
  {"grade":4,"sentence":"Do you know how to help?","usedWords":["do","you","know","how","to","help"]},
  {"grade":4,"sentence":"She is always happy at school.","usedWords":["she","is","always","happy","at","school"]},
  {"grade":4,"sentence":"I think about my family today.","usedWords":["i","think","about","my","family","today"]},
  {"grade":4,"sentence":"Look at the good student now.","usedWords":["look","at","the","good","student","now"]},
  {"grade":4,"sentence":"We can use this in school.","usedWords":["we","can","use","this","in","school"]},
  {"grade":4,"sentence":"I see my friend at school.","usedWords":["i","see","my","friend","at","school"]},
  {"grade":4,"sentence":"Where do you want to go?","usedWords":["where","do","you","want","to","go"]},
  {"grade":4,"sentence":"She can go home with me.","usedWords":["she","can","go","home","with","me"]},
  {"grade":4,"sentence":"I like to think about this.","usedWords":["i","like","to","think","about","this"]},
  {"grade":4,"sentence":"How do you get to school?","usedWords":["how","do","you","get","to","school"]},
  {"grade":4,"sentence":"Take your book home with you.","usedWords":["take","your","book","home","with","you"]},
  {"grade":4,"sentence":"I sometimes play at home today.","usedWords":["i","sometimes","play","at","home","today"]},
  {"grade":4,"sentence":"We always come to school on time.","usedWords":["we","always","come","to","school","on","time"]},
  {"grade":5,"sentence":"What time do we go to school?","usedWords":["what","time","do","we","go","to","school"]},
  {"grade":5,"sentence":"I always need help from my teacher.","usedWords":["i","always","need","help","from","my","teacher"]},
  {"grade":5,"sentence":"I often want to play at school.","usedWords":["i","often","want","to","play","at","school"]},
  {"grade":5,"sentence":"How do you use your pencil today?","usedWords":["how","do","you","use","your","pencil","today"]},
  {"grade":5,"sentence":"I think she is a good friend.","usedWords":["i","think","she","is","a","good","friend"]},
  {"grade":5,"sentence":"I want to take this book home today.","usedWords":["i","want","to","take","this","book","home","today"]},
  {"grade":5,"sentence":"She can always come to my class.","usedWords":["she","can","always","come","to","my","class"]},
  {"grade":5,"sentence":"Do you know who is in my class?","usedWords":["do","you","know","who","is","in","my","class"]},
  {"grade":5,"sentence":"I need to get help from you.","usedWords":["i","need","to","get","help","from","you"]},
  {"grade":5,"sentence":"Where do you go to school today?","usedWords":["where","do","you","go","to","school","today"]},
  {"grade":5,"sentence":"I think you are a good student.","usedWords":["i","think","you","are","a","good","student"]},
  {"grade":5,"sentence":"What do you want to do today?","usedWords":["what","do","you","want","to","do","today"]},
  {"grade":5,"sentence":"She is always happy to help me.","usedWords":["she","is","always","happy","to","help","me"]},
  {"grade":5,"sentence":"We all need to go home now.","usedWords":["we","all","need","to","go","home","now"]},
  {"grade":5,"sentence":"I know about your family at home.","usedWords":["i","know","about","your","family","at","home"]},
  {"grade":5,"sentence":"How do you make it to school?","usedWords":["how","do","you","make","it","to","school"]},
  {"grade":5,"sentence":"She can see the big book at school.","usedWords":["she","can","see","the","big","book","at","school"]},
  {"grade":5,"sentence":"I often think about my good friend.","usedWords":["i","often","think","about","my","good","friend"]},
  {"grade":5,"sentence":"Do you want to use my pencil?","usedWords":["do","you","want","to","use","my","pencil"]},
  {"grade":5,"sentence":"I sometimes go home to my family.","usedWords":["i","sometimes","go","home","to","my","family"]},
  {"grade":5,"sentence":"She is a good student in class.","usedWords":["she","is","a","good","student","in","class"]},
  {"grade":5,"sentence":"What time do you come to school?","usedWords":["what","time","do","you","come","to","school"]},
  {"grade":5,"sentence":"I always want to help my teacher.","usedWords":["i","always","want","to","help","my","teacher"]},
  {"grade":5,"sentence":"We need to use this book today.","usedWords":["we","need","to","use","this","book","today"]},
  {"grade":5,"sentence":"I often need to get help today.","usedWords":["i","often","need","to","get","help","today"]},
  {"grade":5,"sentence":"How do you help your family at home?","usedWords":["how","do","you","help","your","family","at","home"]},
  {"grade":5,"sentence":"Look at the big school from home.","usedWords":["look","at","the","big","school","from","home"]},
  {"grade":5,"sentence":"I know who is in your class.","usedWords":["i","know","who","is","in","your","class"]},
  {"grade":5,"sentence":"She can get her book from me.","usedWords":["she","can","get","her","book","from","me"]},
  {"grade":5,"sentence":"We like to go to school now.","usedWords":["we","like","to","go","to","school","now"]},
  {"grade":5,"sentence":"I think about my teacher at school.","usedWords":["i","think","about","my","teacher","at","school"]},
  {"grade":5,"sentence":"Do you like to go to school?","usedWords":["do","you","like","to","go","to","school"]},
  {"grade":5,"sentence":"I want to take your book home.","usedWords":["i","want","to","take","your","book","home"]},
  {"grade":5,"sentence":"She is always happy about your help.","usedWords":["she","is","always","happy","about","your","help"]},
  {"grade":5,"sentence":"We can all see who is good.","usedWords":["we","can","all","see","who","is","good"]},
  {"grade":5,"sentence":"I need to know about your family.","usedWords":["i","need","to","know","about","your","family"]},
  {"grade":5,"sentence":"How do you play with your friend?","usedWords":["how","do","you","play","with","your","friend"]},
  {"grade":5,"sentence":"She can always use my small pencil.","usedWords":["she","can","always","use","my","small","pencil"]},
  {"grade":5,"sentence":"I want to make this good today.","usedWords":["i","want","to","make","this","good","today"]},
  {"grade":5,"sentence":"We often go to school in time.","usedWords":["we","often","go","to","school","in","time"]},
  {"grade":6,"sentence":"What time do we have to go to school?","usedWords":["what","time","do","we","have","to","go","school"]},
  {"grade":6,"sentence":"I sometimes need help from my teacher at home.","usedWords":["i","sometimes","need","help","from","my","teacher","at","home"]},
  {"grade":6,"sentence":"I always want to play with my good friend.","usedWords":["i","always","want","to","play","with","my","good","friend"]},
  {"grade":6,"sentence":"How do you use your pencil when you are in class?","usedWords":["how","do","you","use","your","pencil","when","are","in","class"]},
  {"grade":6,"sentence":"I think we need to come to school more often.","usedWords":["i","think","we","need","to","come","school","more","often"]},
  {"grade":6,"sentence":"I want to take this big book home today.","usedWords":["i","want","to","take","this","big","book","home","today"]},
  {"grade":6,"sentence":"She can help me see what is in this book.","usedWords":["she","can","help","me","see","what","is","in","this","book"]},
  {"grade":6,"sentence":"He is a good student at my school.","usedWords":["he","is","a","good","student","at","my","school"]},
  {"grade":6,"sentence":"I always get help from my good teacher.","usedWords":["i","always","get","help","from","my","good","teacher"]},
  {"grade":6,"sentence":"What do you think about your teacher at school?","usedWords":["what","do","you","think","about","your","teacher","at","school"]},
  {"grade":6,"sentence":"I often need to go home to my family.","usedWords":["i","often","need","to","go","home","my","family"]},
  {"grade":6,"sentence":"Where do you want to go to school today?","usedWords":["where","do","you","want","to","go","school","today"]},
  {"grade":6,"sentence":"I always like to see my family at home.","usedWords":["i","always","like","to","see","my","family","at","home"]},
  {"grade":6,"sentence":"How do you make time to help your friend?","usedWords":["how","do","you","make","time","to","help","your","friend"]},
  {"grade":6,"sentence":"She can always help me with my school book.","usedWords":["she","can","always","help","me","with","my","school","book"]},
  {"grade":6,"sentence":"I think you need to come to class today.","usedWords":["i","think","you","need","to","come","class","today"]},
  {"grade":6,"sentence":"We all need to help the student at school.","usedWords":["we","all","need","to","help","the","student","at","school"]},
  {"grade":6,"sentence":"I want to know about your family at home.","usedWords":["i","want","to","know","about","your","family","at","home"]},
  {"grade":6,"sentence":"Do you know how to use this pencil today?","usedWords":["do","you","know","how","to","use","this","pencil","today"]},
  {"grade":6,"sentence":"What time do you come to get your book?","usedWords":["what","time","do","you","come","to","get","your","book"]},
  {"grade":6,"sentence":"She is always happy to help me at school.","usedWords":["she","is","always","happy","to","help","me","at","school"]},
  {"grade":6,"sentence":"I sometimes think about my good friend at school.","usedWords":["i","sometimes","think","about","my","good","friend","at","school"]},
  {"grade":6,"sentence":"We need to take all of this home today.","usedWords":["we","need","to","take","all","of","this","home","today"]},
  {"grade":6,"sentence":"How do you know who is in your class?","usedWords":["how","do","you","know","who","is","in","your","class"]},
  {"grade":6,"sentence":"I often go to school to help the teacher.","usedWords":["i","often","go","to","school","help","the","teacher"]},
  {"grade":6,"sentence":"Where do you want to take your family today?","usedWords":["where","do","you","want","to","take","your","family","today"]},
  {"grade":6,"sentence":"She can help me get my book from school.","usedWords":["she","can","help","me","get","my","book","from","school"]},
  {"grade":6,"sentence":"I think we can all use this at home.","usedWords":["i","think","we","can","all","use","this","at","home"]},
  {"grade":6,"sentence":"What do you like to do at home today?","usedWords":["what","do","you","like","to","do","at","home","today"]},
  {"grade":6,"sentence":"She can always come to me when she is sad.","usedWords":["she","can","always","come","to","me","when","is","sad"]},
  {"grade":6,"sentence":"I want to help your family when they come.","usedWords":["i","want","to","help","your","family","when","they","come"]},
  {"grade":6,"sentence":"Where do you go to school most of the time?","usedWords":["where","do","you","go","to","school","most","of","the","time"]},
  {"grade":6,"sentence":"I need to take my pencil to class today.","usedWords":["i","need","to","take","my","pencil","class","today"]},
  {"grade":6,"sentence":"Do you know that she is a good student?","usedWords":["do","you","know","that","she","is","a","good","student"]},
  {"grade":6,"sentence":"We sometimes play at school with my good friend.","usedWords":["we","sometimes","play","at","school","with","my","good","friend"]}
];
